name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build With MSBuild
      run: msbuild ./src/HiFramework.sln -p:Configuration=Release
